### ISSUE TITLE
Support for string module & chunk ids

### ISSUE THREAD

**Issue by Whoaa512** [erykpiast/webpack-stats-explorer#195]
I'm trying to load up some stats files created using the `webpack.NamedChunksPlugin` by creating my own hash.

This breaks with the following error: 
```
Expected number, got "fdef"
  in array at index 0
  at field 'chunks'
  in array at index 1
  at field 'assets'
```

How can I get this working?

**Comment by erykpiast** [comment]
Hi @Whoaa512, thank you for reporting the bug! I suppose it's a mistake in typings I've created for Webpack's stats file. If I took a blind shot, I'd say it's an issue [here](https://github.com/erykpiast/webpack-stats-explorer/blob/master/src/Webpack/WebpackAsset.ml#L3). I don't even use this field (I just want to have a strict type for everything in the structure), but `bs-json` parser doesn't forgive.

I'll change the type to `string`, numbers should be coerced correctly anyway. Could you upload here stat files you're working with, so I can test it before deploying?

**Comment by erykpiast** [comment]
Alright, I reproduced the issue and confirmed that `chunks` list type was a problem. The fixed version is deployed. @Whoaa512 could you check if everything works for you now?
