### ISSUE TITLE
Allow to upload single file and add more after some time

### ISSUE THREAD

**Issue by erykpiast** [erykpiast/webpack-stats-explorer#229]
It may be more convenient for the user to upload reference stats first, then build a code from branch and add another file. This feature may be extended, so adding stat file is a regular part of the application flow, no matter it's the second or the fifth, but till the user uploads two, the comparison is not displayed.

It needs two things some intermediate state in [`WelcomeScreen` component](https://github.com/erykpiast/webpack-stats-explorer/blob/master/src/App/WelcomeScreen.re) (like "Waiting for the second file...") and `Upload` button somewhere, maybe in application header.

**Comment by JeremiAnastaziak** [comment]
Assign me pls

**Comment by erykpiast** [comment]
@JeremiAnastaziak I'll handle this one, no worries :)
